# Generated by Django 3.2.5 on 2021-08-02 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=100, unique=True)),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('project_start_date', models.DateField()),
                ('project_end_date', models.DateField()),
                ('project_budget', models.CharField(max_length=100)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hub')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
