# Generated by Django 3.2.5 on 2021-08-07 08:05

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_description', models.TextField()),
                ('donor_website', models.CharField(max_length=100)),
                ('donor_dates', models.DateField()),
                ('donor_email', models.EmailField(max_length=254)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('donor_contact', models.CharField(max_length=100)),
                ('donation_range', models.IntegerField()),
                ('donation_category', models.CharField(max_length=30)),
                ('donor_type', models.CharField(max_length=30)),
                ('key_contact_name', models.CharField(max_length=100)),
                ('key_contact_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
