# Generated by Django 3.2.5 on 2021-08-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donation_category',
            field=models.CharField(choices=[('Equipment', 'Equipment'), ('Technology', 'Technology'), ('Funds', 'Funds'), ('Mixed', 'Mixed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_type',
            field=models.CharField(choices=[('Philanthropy', 'Philanthropy'), ('Government Organization', 'Government Organization'), ('International Foundation', 'International Foundation')], max_length=30),
        ),
    ]
