# Generated by Django 3.2.5 on 2021-08-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210807_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_contact',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_dates',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_description',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_website',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='donor',
            name='key_contact_email',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='donor',
            name='key_contact_name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
