# Generated by Django 3.2.5 on 2021-08-10 10:45

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210807_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patner_name', models.CharField(max_length=100)),
                ('patner_adress', models.CharField(max_length=250)),
                ('patner_country', django_countries.fields.CountryField(max_length=2)),
                ('key_contact_name', models.CharField(max_length=100)),
                ('key_contact_email', models.EmailField(max_length=254)),
                ('patner_website', models.CharField(blank=True, default=None, max_length=200)),
                ('patner_description', models.TextField(help_text='Short description of the partners expertise and how it fits with Camara')),
                ('patnership_start', models.DateField()),
                ('areas_of_patnership', models.TextField(help_text='Agreed areas of partnership')),
            ],
        ),
        migrations.AlterField(
            model_name='donor',
            name='donation_range',
            field=models.IntegerField(help_text='Range of How much Funds the Donor Normally Provide'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_dates',
            field=models.DateField(blank=True, default=None, help_text='Key Dates for donation or funding application submission'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_description',
            field=models.TextField(blank=True, default=None, help_text='Short Description of the Donor and what the donor normally funds'),
        ),
    ]
