# Generated by Django 3.2.5 on 2021-08-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_partner_patner_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='patner_adress',
            new_name='partner_adress',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='patner_country',
            new_name='partner_country',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='patner_description',
            new_name='partner_description',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='patner_name',
            new_name='partner_name',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='patner_website',
            new_name='partner_website',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='patnership_start',
            new_name='partnership_start',
        ),
    ]
