# Generated by Django 3.2.5 on 2021-08-16 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210810_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_role', models.CharField(blank=True, default=None, max_length=200)),
                ('start_Date', models.DateField(help_text='Date the Partnership in This Project Begins  (Same or different as project dates)')),
                ('end_Date', models.DateField(help_text='Date the Partnership in This Project Ends (Same or different as project dates)')),
                ('key_contact_name_1', models.CharField(blank=True, default=None, max_length=100)),
                ('key_contact_email_1', models.EmailField(blank=True, default=None, max_length=100)),
                ('key_contact_name_2', models.CharField(blank=True, default=None, help_text='(Optional)', max_length=100)),
                ('key_contact_email_2', models.EmailField(blank=True, default=None, help_text='(Optional)', max_length=100)),
                ('partner_Budget', models.IntegerField()),
                ('partner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.partner')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
