# Generated by Django 3.2.5 on 2021-08-17 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_partner',
            name='end_Date',
            field=models.DateField(help_text='Date the Partnership This Project Ends (Same or different as project dates)'),
        ),
        migrations.AlterField(
            model_name='project_partner',
            name='start_Date',
            field=models.DateField(help_text='Date the Partnership This Project Begins  (Same or different as project dates)'),
        ),
        migrations.CreateModel(
            name='Project_Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruitment_source', models.CharField(help_text='How the donor was secured (e.g Funding Application, SCR, etc)', max_length=200)),
                ('type_of_donation', models.CharField(help_text='Type contribution of the funder in the project', max_length=200)),
                ('value_of_donation', models.CharField(help_text='Monetary value of contribution of the funder in the project', max_length=200)),
                ('key_contact_name', models.CharField(max_length=200)),
                ('key_contact_email', models.EmailField(max_length=200)),
                ('donor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.donor')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
