# Generated by Django 3.2.5 on 2021-10-04 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_code', models.CharField(blank=True, default=None, max_length=20, unique=True)),
                ('school_name', models.CharField(max_length=30)),
                ('school_level', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('TVET', 'TVET')], max_length=20)),
                ('school_ownership', models.CharField(choices=[('Government', 'Government'), ('Private', 'Private'), ('Religious', 'Religious'), ('NGO', 'NGO')], max_length=20)),
                ('school_area', models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], max_length=20)),
                ('po_box', models.CharField(blank=True, default=None, max_length=20)),
                ('phone_number_1', models.CharField(blank=True, default=None, max_length=20)),
                ('phone_number_2', models.CharField(blank=True, default=None, max_length=20)),
                ('email', models.EmailField(blank=True, default=None, max_length=20)),
                ('website', models.CharField(blank=True, default=None, max_length=20)),
                ('female_teachers', models.IntegerField()),
                ('male_teachers', models.IntegerField()),
                ('female_students', models.IntegerField()),
                ('male_students', models.IntegerField()),
                ('female_sn_students', models.IntegerField()),
                ('male_sn_students', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hub')),
            ],
        ),
    ]
