# Generated by Django 3.2.5 on 2021-10-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20211004_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
