# Generated by Django 3.2.5 on 2021-11-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_school_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='phone_number_1',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone_number_2',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='po_box',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_area',
            field=models.CharField(blank=True, choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_level',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('TVET', 'TVET')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_ownership',
            field=models.CharField(blank=True, choices=[('Government', 'Government'), ('Private', 'Private'), ('Religious', 'Religious'), ('NGO', 'NGO')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='website',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
