# Generated by Django 3.2.5 on 2022-02-11 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_school_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='County_Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_or_region_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_County_Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_county_or_Zone_name', models.CharField(max_length=30)),
                ('county_or_region_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.county_region')),
            ],
        ),
        migrations.CreateModel(
            name='District_Woreda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_or_woreda_name', models.CharField(max_length=30)),
                ('county_or_region_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.county_region')),
                ('sub_county_or_Zone_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.sub_county_zone')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='county_or_region_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.county_region'),
        ),
        migrations.AddField(
            model_name='school',
            name='district_or_woreda_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.district_woreda'),
        ),
        migrations.AddField(
            model_name='school',
            name='sub_county_or_Zone_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.sub_county_zone'),
        ),
    ]
