# Generated by Django 3.2.5 on 2022-02-11 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_user_education_level'),
        ('school', '0007_auto_20220211_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='county_region',
            name='hub_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hub'),
        ),
    ]
