# Generated by Django 3.2.5 on 2022-02-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_county_region_hub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='district_or_woreda_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
