# Generated by Django 3.2.5 on 2022-02-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20220218_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_county_zone',
            name='sub_county_or_Zone_name',
            field=models.CharField(max_length=100),
        ),
    ]
