# Generated by Django 3.2.5 on 2022-02-22 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220215_0014'),
        ('school', '0011_alter_sub_county_zone_sub_county_or_zone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_county_zone',
            name='hub_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hub'),
        ),
    ]
