# Generated by Django 3.2.5 on 2022-04-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_school_school_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_level',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('TVET', 'TVET'), ('Integrated', 'Integrated')], default=None, max_length=20, null=True),
        ),
    ]
