# Generated by Django 3.2.5 on 2021-10-25 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0009_auto_20210817_0646'),
        ('school', '0003_alter_school_email'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer_Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('phone_number', models.IntegerField()),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hub')),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='Computer_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Invoice Number', max_length=100)),
                ('number_of_computers', models.IntegerField(help_text='Number of computers requesting')),
                ('computer_type', models.CharField(blank=True, choices=[('System Unit', 'System Unit'), ('Tablet', 'Tablet'), ('Laptop', 'Laptop'), ('Printer', 'Printer'), ('Projector', 'Projector')], default=None, help_text='If its laptop, CPU, tablet etc', max_length=30)),
                ('computer_status', models.CharField(blank=True, choices=[('New', 'New'), ('Refurbished', 'Refurbished'), ('Used', 'Used')], default=None, max_length=30)),
                ('processor_type', models.CharField(blank=True, choices=[('intel i3', 'intel i3'), ('intel i5', 'intel i5'), ('intel i7', 'intel i7'), ('Dual Core', 'Dual Core')], default=None, max_length=30)),
                ('processor_speed', models.CharField(blank=True, default=None, max_length=30)),
                ('memory_type', models.CharField(blank=True, choices=[('DRAM', 'DRAM'), ('SRAM', 'SRAM')], default=None, max_length=30)),
                ('memory_size', models.CharField(blank=True, choices=[('512MB', '512MB'), ('1GB', '1GB'), ('2GB', '2GB'), ('4GB', '4GB'), ('8GB', '8GB')], default=None, max_length=30)),
                ('storage_type', models.CharField(blank=True, choices=[('SDD', 'SSD'), ('HDD', 'HDD'), ('ROM', 'ROM'), ('SD Card', 'SD Card')], default=None, max_length=30)),
                ('storage_size', models.CharField(blank=True, choices=[('80GB', '80GB'), ('128GB', '128GB'), ('160GB', '160GB'), ('250GB', '250GB'), ('320GB', '320GB'), ('500GB', '500GB'), ('1TB', '1TB')], default=None, max_length=30)),
                ('os_type', models.CharField(blank=True, choices=[('Mac OS', 'Mac OS'), ('Windows', 'Windows'), ('Linux', 'Linux')], default=None, max_length=30)),
                ('os_version', models.CharField(blank=True, default=None, max_length=30)),
                ('request_notes', models.CharField(blank=True, default=None, max_length=250)),
                ('request_status', models.IntegerField(blank=True, default=0)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch.computer_applicant')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hub')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_affritrack_number', models.CharField(max_length=50)),
                ('m_affritrack_number', models.CharField(max_length=50)),
                ('date_dispatched', models.DateField()),
                ('warranty_end', models.DateField()),
                ('applicant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch.computer_applicant')),
                ('computer_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch.computer_request')),
                ('dispatched_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hub')),
            ],
        ),
    ]
