# Generated by Django 3.2.5 on 2021-10-29 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_school_email'),
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='school_name',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AlterField(
            model_name='computer_request',
            name='invoice_number',
            field=models.CharField(blank=True, default=None, help_text='Invoice Number', max_length=100),
        ),
    ]
