# Generated by Django 3.2.5 on 2021-10-29 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_school_email'),
        ('dispatch', '0002_auto_20211029_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='school_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
    ]
