# Generated by Django 3.2.5 on 2021-10-29 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210817_0646'),
        ('dispatch', '0003_alter_dispatch_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_request',
            name='project',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
