# Generated by Django 3.2.5 on 2021-10-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_alter_computer_request_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer_request',
            name='time_created',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
