# Generated by Django 3.2.5 on 2021-11-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0007_alter_computer_request_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_request',
            name='invoice_number',
            field=models.CharField(blank=True, default=None, help_text='Invoice Number', max_length=100, null=True),
        ),
    ]
