# Generated by Django 3.2.5 on 2021-11-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0010_alter_computer_request_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_request',
            name='memory_size',
            field=models.CharField(blank=True, choices=[('512 MB', '512 MB'), ('1 GB', '1 GB'), ('2 GB', '2 GB'), ('4 GB', '4 GB'), ('8 GB', '8 GB')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computer_request',
            name='storage_size',
            field=models.CharField(blank=True, choices=[('80 GB', '80 GB'), ('128 GB', '128 GB'), ('160 GB', '160 GB'), ('250 GB', '250 GB'), ('320 GB', '320 GB'), ('500 GB', '500 GB'), ('1TB', '1TB')], default=None, max_length=30, null=True),
        ),
    ]
