# Generated by Django 3.2.5 on 2021-12-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0011_auto_20211111_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_request',
            name='computer_status',
            field=models.CharField(blank=True, choices=[('Refurbished', 'Refurbished'), ('New', 'New'), ('Used', 'Used')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computer_request',
            name='os_type',
            field=models.CharField(blank=True, choices=[('Linux', 'Linux'), ('Mac OS', 'Mac OS'), ('Windows', 'Windows'), ('Android', 'Android'), ('No OS', 'No OS')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computer_request',
            name='processor_type',
            field=models.CharField(blank=True, choices=[('intel i3', 'intel i3'), ('intel i5', 'intel i5'), ('intel i7', 'intel i7'), ('Dual Core', 'Dual Core'), ('Pentium 4', 'Pentium 4'), ('Quad Core', 'Quad Core'), ('AMD', 'AMD')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computer_request',
            name='storage_size',
            field=models.CharField(blank=True, choices=[('80 GB', '80 GB'), ('128 GB', '128 GB'), ('160 GB', '160 GB'), ('250 GB', '250 GB'), ('320 GB', '320 GB'), ('500 GB', '500 GB'), ('1TB', '1TB'), ('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computer_request',
            name='storage_type',
            field=models.CharField(blank=True, choices=[('HDD', 'HDD'), ('SDD', 'SSD'), ('ROM', 'ROM'), ('SD Card', 'SD Card')], default=None, max_length=30, null=True),
        ),
    ]
