# Generated by Django 3.2.5 on 2022-03-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0012_auto_20211214_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_request',
            name='storage_size',
            field=models.CharField(blank=True, choices=[('80 GB', '80 GB'), ('128 GB', '128 GB'), ('160 GB', '160 GB'), ('250 GB', '250 GB'), ('320 GB', '320 GB'), ('500 GB', '500 GB'), ('1 TB', '1 TB'), ('8 GB', '8 GB'), ('16 GB', '16 GB'), ('32 GB', '32 GB')], default=None, max_length=30, null=True),
        ),
    ]
