# Generated by Django 3.2.5 on 2021-08-02 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(max_length=50, unique=True)),
                ('department_name', models.CharField(max_length=100)),
                ('department_email', models.EmailField(blank=True, default=None, max_length=254)),
                ('department_phone_number', models.CharField(blank=True, default=None, max_length=30)),
                ('department_role', models.TextField()),
                ('department_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_code', models.CharField(max_length=20, unique=True)),
                ('hub_name', models.CharField(max_length=100)),
                ('hub_located_country', models.CharField(choices=[('Ireland', 'Ireland'), ('Ethiopia', 'Ethiopia'), ('Kenya', 'Kenya'), ('Tanzania', 'Tanzania'), ('Zambia', 'Zambia'), ('Lesotho', 'Lesotho')], max_length=30)),
                ('hub_address', models.TextField()),
                ('hub_email', models.EmailField(max_length=254)),
                ('hub_phone', models.CharField(max_length=50)),
                ('hub_registration_year', models.DateField()),
                ('hub_registration_number', models.CharField(max_length=100)),
                ('hub_registration_status', models.CharField(choices=[('NGO', 'NGO'), ('Limited Company', 'Limited Company')], max_length=30)),
                ('hub_tin_number', models.CharField(max_length=100)),
                ('hub_website', models.CharField(blank=True, default=None, help_text='Optional', max_length=100)),
                ('hub_facebook', models.CharField(blank=True, default=None, help_text='Optional', max_length=100)),
                ('hub_instagram', models.CharField(blank=True, default=None, help_text='Optional', max_length=100)),
                ('hub_twitter', models.CharField(blank=True, default=None, help_text='Optional', max_length=100)),
                ('hub_linkedin', models.CharField(blank=True, default=None, help_text='Optional', max_length=100)),
                ('hub_youtube', models.CharField(blank=True, default=None, help_text='Optional', max_length=100)),
                ('hub_status', models.IntegerField(default=1)),
                ('hub_country_director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100)),
                ('position_description', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hub')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=100, unique=True)),
                ('user_personal_email', models.EmailField(default='ephrem@gmail.com', max_length=254)),
                ('user_hired_date', models.DateField()),
                ('user_employement_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Part time', 'Part time')], max_length=20)),
                ('user_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('user_phone_number', models.CharField(max_length=30)),
                ('user_education_level', models.CharField(choices=[('Bachelor’s', 'Bachelor’s'), ('Master’s', 'Master’s'), ('Doctoral', 'Doctoral')], max_length=20)),
                ('user_birth_date', models.DateField()),
                ('user_contact_name', models.CharField(default='ephrem@gmail.com', max_length=100)),
                ('user_contact_phone_number', models.CharField(default='ephrem@gmail.com', max_length=30)),
                ('user_contact_email', models.EmailField(default='ephrem@gmail.com', max_length=254)),
                ('user_contact_address', models.TextField(default='ephrem@gmail.com')),
                ('user_contact_relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Spouse', 'Spouse'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Sibiling', 'Sibiling')], max_length=30)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hub')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hub'),
        ),
    ]
