# Generated by Django 3.2.5 on 2021-12-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_education_level',
            field=models.CharField(choices=[('Bachelor’s', 'Bachelor’s'), ('Master’s', 'Master’s'), ('Doctoral', 'Doctoral'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('Secondary Education', 'Secondary Education')], max_length=20),
        ),
    ]
