# Generated by Django 3.2.5 on 2022-02-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220214_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_contact_address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
