# Generated by Django 3.2.5 on 2022-02-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_user_contact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='hub_address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
