# Generated by Django 3.2.5 on 2022-02-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_hub_hub_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_role',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_description',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
