# Generated by Django 3.2.5 on 2022-03-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_t_officer',
            field=models.BooleanField(default=False, verbose_name='User status'),
        ),
    ]
