# Generated by Django 3.2.5 on 2022-03-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_is_t_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_t_officer',
            field=models.BooleanField(default=False, verbose_name='Technical Officer status'),
        ),
    ]
