# Generated by Django 3.2.5 on 2021-10-25 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210817_0646'),
        ('accounts', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.CharField(help_text='Short course description', max_length=250),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(help_text='The name of the course', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='hub',
            field=models.ForeignKey(help_text='The hub the course is designed for.', on_delete=django.db.models.deletion.CASCADE, to='accounts.hub'),
        ),
        migrations.AlterField(
            model_name='course',
            name='project',
            field=models.ForeignKey(help_text='The project the course is designed for.', on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
