# Generated by Django 3.2.5 on 2021-08-31 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0009_auto_20210817_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_affritrack_number', models.CharField(max_length=50, unique=True)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('brand', models.CharField(choices=[('Dell', 'Dell'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Acer', 'Acer'), ('Asus', 'Asus')], max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('container_number', models.CharField(max_length=20)),
                ('device_status', models.CharField(choices=[('New', 'New'), ('Refurbished', 'Refurbished'), ('Used', 'Used')], max_length=20)),
                ('processor_type', models.CharField(choices=[('intel i3', 'intel i3'), ('intel i5', 'intel i5'), ('intel i7', 'intel i7'), ('Dual Core', 'Dual Core')], max_length=20)),
                ('processor_speed', models.CharField(max_length=10)),
                ('memory_type', models.CharField(choices=[('DRAM', 'DRAM'), ('SRAM', 'SRAM')], max_length=10)),
                ('memory_size', models.CharField(choices=[('512MB', '512MB'), ('1GB', '1GB'), ('2GB', '2GB'), ('4GB', '4GB'), ('8GB', '8GB')], max_length=10)),
                ('storage_type', models.CharField(choices=[('SDD', 'SSD'), ('HDD', 'HDD'), ('ROM', 'ROM'), ('SD Card', 'SD Card')], max_length=10)),
                ('storage_size', models.CharField(choices=[('80GB', '80GB'), ('128GB', '128GB'), ('160GB', '160GB'), ('250GB', '250GB'), ('320GB', '320GB'), ('500GB', '500GB'), ('1TB', '1TB')], max_length=10)),
                ('os_type', models.CharField(choices=[('Mac OS', 'Mac OS'), ('Windows', 'Windows'), ('Linux', 'Linux')], max_length=10)),
                ('os_version', models.CharField(max_length=30)),
                ('working_status', models.CharField(choices=[('Working', 'Working'), ('Problematic', 'Problematic'), ('Dispatched', 'Dispatched'), ('Processed', 'Processed')], max_length=30)),
                ('date_received', models.DateField()),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.donor')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.supplier')),
            ],
        ),
    ]
