# Generated by Django 3.2.5 on 2021-09-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='device_type',
            field=models.CharField(choices=[('System Unit', 'System Unit'), ('Tablet', 'Tablet'), ('Laptop', 'Laptop'), ('Printer', 'Printer'), ('Projector', 'Projector')], default='System Unit', max_length=20),
        ),
        migrations.AddField(
            model_name='computer',
            name='screen_size',
            field=models.CharField(default='21', max_length=20),
        ),
        migrations.AlterField(
            model_name='computer',
            name='working_status',
            field=models.CharField(choices=[('Working', 'Working'), ('Problematic', 'Problematic'), ('Dispatched', 'Dispatched'), ('Processed', 'Processed'), ('E-Waste', 'E-Waste')], max_length=30),
        ),
    ]
