# Generated by Django 3.2.5 on 2021-09-23 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210817_0646'),
        ('products', '0002_auto_20210904_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_affritrack_number', models.CharField(max_length=50, unique=True)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('brand', models.CharField(choices=[('Dell', 'Dell'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Acer', 'Acer'), ('Asus', 'Asus')], max_length=20)),
                ('container_number', models.CharField(max_length=20)),
                ('device_status', models.CharField(choices=[('New', 'New'), ('Refurbished', 'Refurbished'), ('Used', 'Used')], max_length=20)),
                ('date_received', models.DateField()),
                ('screen_size', models.CharField(default='21', max_length=20)),
                ('working_status', models.CharField(choices=[('Working', 'Working'), ('Problematic', 'Problematic'), ('Dispatched', 'Dispatched'), ('Processed', 'Processed'), ('E-Waste', 'E-Waste')], max_length=30)),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.donor')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.supplier')),
            ],
        ),
    ]
