# Generated by Django 3.2.5 on 2021-11-11 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210817_0646'),
        ('products', '0003_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='device_status',
            field=models.CharField(choices=[('New', 'New'), ('Refurbished', 'Refurbished'), ('Used', 'Used')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='donor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.donor'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os_type',
            field=models.CharField(choices=[('Mac OS', 'Mac OS'), ('Windows', 'Windows'), ('Linux', 'Linux')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os_version',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.supplier'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='working_status',
            field=models.CharField(choices=[('Working', 'Working'), ('Problematic', 'Problematic'), ('Dispatched', 'Dispatched'), ('Processed', 'Processed'), ('E-Waste', 'E-Waste')], default='Working', max_length=30),
        ),
    ]
