# Generated by Django 3.2.5 on 2021-11-11 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0004_auto_20211111_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='hub',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hub'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='hub',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hub'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='memory_size',
            field=models.CharField(choices=[('512 MB', '512 MB'), ('1 GB', '1 GB'), ('2 GB', '2 GB'), ('4 GB', '4 GB'), ('8 GB', '8 GB')], max_length=10),
        ),
        migrations.AlterField(
            model_name='computer',
            name='storage_size',
            field=models.CharField(choices=[('80 GB', '80 GB'), ('128 GB', '128 GB'), ('160 GB', '160 GB'), ('250 GB', '250 GB'), ('320 GB', '320 GB'), ('500 GB', '500 GB'), ('1TB', '1TB')], max_length=10),
        ),
    ]
