# Generated by Django 3.2.5 on 2021-12-07 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210817_0646'),
        ('products', '0008_alter_monitor_working_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='donor_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.donor'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.supplier'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='donor_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.donor'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.supplier'),
        ),
    ]
