# Generated by Django 3.2.5 on 2021-12-10 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_user_education_level'),
        ('products', '0009_auto_20211207_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='device_status',
            field=models.CharField(choices=[('New', 'New'), ('Refurbished', 'Refurbished'), ('Used', 'Used')], default='Refurbished', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='hub',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hub'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='device_status',
            field=models.CharField(choices=[('New', 'New'), ('Refurbished', 'Refurbished'), ('Used', 'Used')], default='Refurbished', max_length=20, null=True),
        ),
    ]
