# Generated by Django 3.2.5 on 2021-12-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20211214_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=240, null=True),
        ),
    ]
