# Generated by Django 3.2.5 on 2021-12-23 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20211214_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operating_System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='computer',
            name='os_type',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os_version',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='Operating_system_Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_version', models.CharField(max_length=100)),
                ('os_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.operating_system')),
            ],
        ),
    ]
