# Generated by Django 3.2.5 on 2021-12-23 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20211223_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='os_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.operating_system'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os_version',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.operating_system_version'),
        ),
    ]
