# Generated by Django 3.2.5 on 2022-02-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20211223_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='working_status',
            field=models.CharField(choices=[('Working', 'Working'), ('Processed', 'Processed'), ('Problematic', 'Problematic'), ('E-Waste', 'E-Waste'), ('Not Received', 'Not Received')], default='Working', max_length=30),
        ),
    ]
