# Generated by Django 3.2.5 on 2022-02-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_computer_working_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='working_status',
            field=models.CharField(choices=[('Processed', 'Processed'), ('Problematic', 'Problematic'), ('E-Waste', 'E-Waste'), ('Not Received', 'Not Received')], default='Processed', max_length=30),
        ),
    ]
