# Generated by Django 3.2.5 on 2022-02-18 13:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20220214_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_category',
            field=models.CharField(blank=True, choices=[('Local', 'Local'), ('International', 'International')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_email_2',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_items',
            field=models.CharField(blank=True, default=None, help_text='ie. Laptops, Printers, Desktops, Networking Materials, Accessories, Tablets, Electric Supplies. Please use comma(,) to separate the items.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_items_status',
            field=models.CharField(blank=True, help_text='ie. Brand New, Used, Refurb, Both. Please use comma(,) to separate the items.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_website',
            field=models.CharField(blank=True, default=None, help_text='Optional', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Chequie', 'Chequie'), ('Bank Transfer', 'Bank Transfer')], default=None, max_length=20),
        ),
    ]
