# Generated by Django 3.2.5 on 2022-02-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_monitor_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='c_affritrack_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='m_affritrack_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
