# Generated by Django 3.2.5 on 2022-03-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20220301_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='brand',
            field=models.CharField(choices=[('Dell', 'Dell'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Acer', 'Acer'), ('Asus', 'Asus'), ('Epson', 'Epson'), ('MediTech', 'MediTech'), ('Samsung', 'Samsung'), ('X_Tig', 'X_Tig'), ('Fujitsu', 'Fujitsu'), ('Clone', 'Clone'), ('P.C Peripherals', 'P.C Peripherals'), ('Stone PC', 'Stone PC'), ('System manufacturer', 'System manufacturer'), ('AOC', 'AOC'), ('Belinea', 'Belinea'), ('Benq', 'Benq'), ('gnr', 'gnr'), ('Hanns-G', 'Hanns-G'), ('Iiyama', 'Iiyama'), ('Lacie', 'Lacie'), ('LG', 'LG'), ('NEC', 'NEC'), ('Philips', 'Philips'), ('ViewSonic', 'ViewSonic')], max_length=20),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='brand',
            field=models.CharField(choices=[('Dell', 'Dell'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Acer', 'Acer'), ('Asus', 'Asus'), ('Epson', 'Epson'), ('MediTech', 'MediTech'), ('Samsung', 'Samsung'), ('X_Tig', 'X_Tig'), ('Fujitsu', 'Fujitsu'), ('Clone', 'Clone'), ('P.C Peripherals', 'P.C Peripherals'), ('Stone PC', 'Stone PC'), ('System manufacturer', 'System manufacturer'), ('AOC', 'AOC'), ('Belinea', 'Belinea'), ('Benq', 'Benq'), ('gnr', 'gnr'), ('Hanns-G', 'Hanns-G'), ('Iiyama', 'Iiyama'), ('Lacie', 'Lacie'), ('LG', 'LG'), ('NEC', 'NEC'), ('Philips', 'Philips'), ('ViewSonic', 'ViewSonic')], max_length=20),
        ),
    ]
