# Generated by Django 3.2.5 on 2022-03-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20220303_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='memory_type',
            field=models.CharField(choices=[('DRAM', 'DRAM'), ('SRAM', 'SRAM'), ('XEON', 'XEON')], default='DRAM', max_length=10),
        ),
    ]
